.set rax_offset, 0
.set rbx_offset, 8
.set rcx_offset, 16
.set rdx_offset, 24
.set rsi_offset, 32
.set rdi_offset, 40
.set r8_offset,  48
.set r9_offset,  56
.set r10_offset, 64
.set r11_offset, 72
.set r12_offset, 80
.set r13_offset, 88
.set r14_offset, 96
.set r15_offset, 104
.set rbp_offset, 112

.set rflags_offset, 120

.set xmm0_offset, 128
.set xmm1_offset, 144
.set xmm2_offset, 160
.set xmm3_offset, 176
.set xmm4_offset, 192
.set xmm5_offset, 208

.set rsp_offset, 224
.set rip_offset, 232
.set dr7_offset, 240